### ISSUE TITLE
AttributeError: module 'neopixel' has no attribute 'GRB'

### ISSUE THREAD

**Issue by brisbaneroboticsclub** [SuperMakeSomething/neopixel-led-mirror#1]
pi@raspberrypi:~/neopixel-led-mirror $ python3 neopixelMirror.py
Traceback (most recent call last):
  File "neopixelMirror.py", line 69, in <module>
    colorOrder = neopixel.GRB
AttributeError: module 'neopixel' has no attribute 'GRB'

**Comment by andrew-lyons** [comment]
@brisbaneroboticsclub, sometimes I have fixed the issue by running sudo python3 instead of just python3.

Alternatively, perhaps the neopixel lib wasn't installed 100% according to the guide? I've had this issue and resolved it by re-installing the lib. 

Uberguide: [https://learn.adafruit.com/adafruit-neopixel-uberguide/python-circuitpython](url)

**Comment by AndKe** [comment]
I have reinstalled, same issue..
Following this guide https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage on a fresh, updated  RPi.
```
pi@raspberrypi:~ $ python3 neopixel.py 
Traceback (most recent call last):
  File "neopixel.py", line 4, in <module>
    import neopixel
  File "/home/pi/neopixel.py", line 16, in <module>
    ORDER = neopixel.GRB
AttributeError: module 'neopixel' has no attribute 'GRB'
```

**Comment by jnkumar1964** [comment]
cannot find the neopixel library mentioned on the link given
